name: primero
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  font_awesome_flutter: ^10.4.0
  equatable: ^2.0.7
  flutter_riverpod: ^2.6.1
  json_annotation: ^4.9.0
  flutter_secure_storage: ^9.0.0 
  dio: ^5.8.0+1
  image_picker: ^1.1.0
  uuid: ^4.3.3 
  retrofit: ^4.4.2          
  freezed_annotation: ^2.4.4
  shared_preferences: ^2.5.3
  barcode_widget: ^2.0.4
  package_info_plus: ^8.0.0
  lottie: ^3.1.2
  intl: ^0.19.0
  
  geolocator: ^14.0.1
  google_maps_flutter: ^2.12.2

dev_dependencies:
  build_runner: ^2.4.0
  json_serializable: ^6.6.0
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  retrofit_generator: ^8.1.0
  freezed: ^2.5.2
  flutter_launcher_icons: ^0.13.1
flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/lottie/
  fonts:
    - family: RedHatDisplay
      fonts:
        - asset: assets/fonts/RedHatDisplay-Regular.ttf
          weight: 400
        - asset: assets/fonts/RedHatDisplay-Medium.ttf
          weight: 500
        - asset: assets/fonts/RedHatDisplay-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/RedHatDisplay-Bold.ttf
          weight: 700

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true 
  image_path: "assets/images/babyTree.png" 
  adaptive_icon_background: "#FFFFFF" 
  min_sdk_android: 21